### ISSUE TITLE
[Android] 달력 날짜 선택 로직 완성, 달력 페이지 지우기, 건너

### ISSUE THREAD

**Issue by HyungMinKang** [hwicode/airbnb#36]
:notebook: Description
----
- 콜백 함수를 통해 선택한 날짜를 ViewModel 에서 각각 분기 처리
- flow 를 통해 분기된 체크인, 체크아웃 날짜 데이터를 BindingAdapter 를 통해 화면에 표시
-  BindingAdapter를 통해 날짜 선택했을 때 배경색 변경 완료
- 각 어댑터의 메서드 호출을 통해 ViewModel 에서 생성한 체크인, 체크아웃 LocalDate 객체 전달
- 체크인/체크아웃 날짜 선택시 UI 변경 로직 완성 ( UI 변경을 위해 drawble 파일 정의)
- 선택가능한 날짜중 가장 첫날짜 UI 변경 로직 적용
- 하단 건너뛰기/ 지우기 버튼 로직 구현 (checkIn/checkOut 값 입력여부에 따라 활성화/비활성화)
- 상단 체크버튼 로직 구현 ( 모든 값 입력시 selected=true로 설정)
- 기존 테스트를 위해 로그인에서 정보 입력화면으로 넘어갔던 부분을 검색화면에서 넘어가도록 수정
- 검색화면에서 검색결과의 각 아이템에 클릭 리스너를 등록, 클릭시 정보입력 페이지로 이동하도록 구현
- 달력 화면에 체크버튼클릭시 가격페이지 이동 로직 완성
- 가격 페이지에 PriceRangeSeekBar 뷰추가

**Comment by cherrylime69** [comment]
수고하셨습니다 산타 할아버지.
